services:
    api_getway:
        build:
            context: ./api-getway-new
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            REDIS_HOST: 'redis'
            MONGO_URL: 'mongodb://mongo:27017'
        depends_on:
            - redis 
        networks:
         - app-network        
    ms1:
        build:
            context: ./microservice-one
            dockerfile: Dockerfile  
        networks:
         - app-network   
        environment:
          REDIS_HOST: 'redis'
          MONGO_URL: 'mongodb://mongo:27017'
    ms2:
        build:
            context: ./microservice-two
            dockerfile: Dockerfile  
        networks:
         - app-network   
        environment:
          REDIS_HOST: 'redis'
          MONGO_URL: 'mongodb://mongo:27017'        
    redis:
       image: 'redis:alpine'
       ports:
          - '6379:6379'
       networks:
         - app-network   
    mongo: 
       image: mongo
       ports:
           - "27017:27017"
       networks:
         - app-network    

networks:
  app-network:
    driver: bridge